// angular-react/react-js/src/components/TodoItem/TodoItem.tsx
import type { TodoType } from '../../types/todo-type';
import deleteIcon from '../../assets/icons/delete-icon.svg';
import './TodoItem.scss';

interface TodoItemProps {
  title: string;
  type: TodoType;
  isDone: boolean;
  id: string;
  onComplete: (id: string) => void;
  onIncomplete: (id: string) => void;
  onDelete: (id: string) => void;
}

export function TodoItem({ title, type, isDone, id, onComplete, onIncomplete, onDelete }: TodoItemProps) {
  function handleClickCheck() {
    if (!isDone) onComplete(id);
    else onIncomplete(id);
  }

  function handleClickDelete() {
    if (confirm(`Delete "${title}"?`)) onDelete(id);
  }

  return (
    <li className={`todo-item ${type} ${isDone ? 'done' : ''}`}>
      <div className="checkbox" onClick={handleClickCheck} />
      <p>{title}</p>
      <button onClick={handleClickDelete}>
        <img alt="Trash icon indicating delete" src={deleteIcon} />
      </button>
    </li>
  );
}

// angular-react/angular-js/src/app/todo-item/todo-item.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

import { TodoType } from '../todo-type';

@Component({
  selector: 'todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.scss']
})
export class TodoItemComponent {

  @Input() title: string= '';
  @Input() type: TodoType = 'normal';
  @Input() isDone: boolean = false;
  @Input() id: string = '';

  @Output() onDelete = new EventEmitter<string>();
  @Output() onComplete = new EventEmitter<string>();
  @Output() onIncomplete = new EventEmitter<string>();

  handleClickCheck(){
    if(!this.isDone) this.onComplete.emit(this.id)
    else this.onIncomplete.emit(this.id)
  }

  handleClickDelete(){
    if(confirm(`Delete "${this.title}"?`)) this.onDelete.emit(this.id)
  }
}
